"""Expressibility analysis for quantum encodings.

This module implements expressibility computation as defined by Sim et al. (2019).
Expressibility measures how well a parameterized quantum circuit can explore
the Hilbert space of quantum states compared to Haar-random states.

Mathematical Background
-----------------------
Expressibility is quantified by comparing the distribution of fidelities
between random quantum states generated by the encoding to the distribution
expected from Haar-random states. The Kullback-Leibler (KL) divergence between
these distributions measures how "expressive" the encoding is:

    Expr = D_KL(P_encoding || P_Haar)

Lower KL divergence indicates higher expressibility (closer to Haar-random).

**Fidelity Sampling**

For each random input pair (x₁, x₂), we:

1. Encode to quantum states: |ψ(x₁)⟩ and |ψ(x₂)⟩
2. Compute fidelity: F = |⟨ψ(x₁)|ψ(x₂)⟩|²
3. Build histogram P_encoding(F) of sampled fidelities

**Haar Distribution**

The theoretical distribution of fidelities for Haar-random states in
d-dimensional Hilbert space (d = 2^n_qubits) is:

    P_Haar(F) = (d - 1)(1 - F)^(d-2)

For large d, this distribution is heavily concentrated near F = 0, reflecting
that random high-dimensional states are typically nearly orthogonal.

**KL Divergence**

The KL divergence measures the "distance" between distributions:

    D_KL(P || Q) = Σᵢ P(xᵢ) log(P(xᵢ) / Q(xᵢ))

**Normalization**

The raw KL divergence is normalized to [0, 1] for interpretability:

    expressibility = 1 - min(1, D_KL / D_max)

where D_max is a chosen maximum KL divergence (default: 10.0).

This module provides:

- :func:`compute_expressibility`: Main function returning expressibility score
- :func:`compute_fidelity_distribution`: Compute fidelity distribution only
- :func:`compute_haar_distribution`: Compute theoretical Haar distribution

References
----------
.. [1] Sim, S., Johnson, P. D., & Aspuru-Guzik, A. (2019).
       "Expressibility and entangling capability of parameterized quantum
       circuits for hybrid quantum-classical algorithms."
       Advanced Quantum Technologies, 2(12), 1900070.
       DOI: 10.1002/qute.201900070

.. [2] Życzkowski, K., & Sommers, H.-J. (2001).
       "Induced measures in the space of mixed quantum states."
       Journal of Physics A, 34(35), 7111.

.. [3] Hubregtsen, T., Pichlmeier, J., Stecher, P., & Bertels, K. (2021).
       "Evaluation of parameterized quantum circuits: on the relation between
       classification accuracy, expressibility, and entangling capability."
       Quantum Machine Intelligence, 3(1), 1-19.

Examples
--------
Basic usage:

>>> from encoding_atlas import AngleEncoding, IQPEncoding
>>> from encoding_atlas.analysis import compute_expressibility
>>>
>>> # Simple non-entangling encoding (low expressibility)
>>> enc_simple = AngleEncoding(n_features=4)
>>> expr_simple = compute_expressibility(enc_simple, n_samples=1000, seed=42)
>>> print(f"AngleEncoding expressibility: {expr_simple:.4f}")
AngleEncoding expressibility: ...

>>> # Entangling encoding (higher expressibility)
>>> enc_iqp = IQPEncoding(n_features=4, reps=2)
>>> expr_iqp = compute_expressibility(enc_iqp, n_samples=1000, seed=42)
>>> print(f"IQPEncoding expressibility: {expr_iqp:.4f}")
IQPEncoding expressibility: ...

Getting full result with distributions:

>>> result = compute_expressibility(enc_iqp, return_distributions=True, seed=42)
>>> print(f"KL Divergence: {result['kl_divergence']:.4f}")
>>> print(f"Samples used: {result['n_samples']}")

Notes
-----
- Computation requires circuit simulation, which scales exponentially with qubits
- For n_qubits > 10, consider using approximate methods or reducing sample count
- Results are stochastic; use seed parameter for reproducibility
- Higher expressibility values indicate the encoding can explore more of the
  Hilbert space, which is generally desirable for variational algorithms

Performance Guidelines
----------------------
Expressibility computation requires quantum circuit simulation, which scales
exponentially with the number of qubits. The following table provides approximate
execution times based on benchmarks on a typical CPU (Intel i7, 2020 era, single
thread). Actual times may vary depending on hardware and system load.

+----------+-----------+---------------+------------------+
| n_qubits | n_samples | Approx. Time  | Memory (approx.) |
+==========+===========+===============+==================+
| 2        | 1000      | ~2-4 seconds  | < 100 MB         |
+----------+-----------+---------------+------------------+
| 4        | 1000      | ~5-10 seconds | < 100 MB         |
+----------+-----------+---------------+------------------+
| 4        | 5000      | ~25-50 sec    | < 200 MB         |
+----------+-----------+---------------+------------------+
| 6        | 1000      | ~15-30 sec    | < 200 MB         |
+----------+-----------+---------------+------------------+
| 8        | 1000      | ~60-120 sec   | ~500 MB          |
+----------+-----------+---------------+------------------+
| 10       | 500       | ~3-5 minutes  | ~2 GB            |
+----------+-----------+---------------+------------------+
| 12+      | any       | Not recommended without sampling reduction |
+----------+-----------+---------------+------------------+

**Scaling Considerations:**

- **Time Complexity**: O(n_samples × 2^n_qubits) due to statevector simulation
- **Memory Complexity**: O(2^n_qubits) for storing statevectors
- Doubling n_samples approximately doubles execution time
- Each additional qubit approximately doubles both time and memory
- For n_qubits > 10, a warning is issued and reduced samples are recommended

**Recommendations for Large Encodings:**

1. Use n_samples=500 or less for exploratory analysis with >8 qubits
2. For production analysis, use n_samples ≥ 2000 with ≤6 qubits
3. Set a random seed for reproducibility when comparing encodings
4. Consider running large computations in parallel for multiple encodings

See Also
--------
compute_entanglement_capability : Related metric for entanglement generation.
count_resources : Analyze computational resources of encodings.
estimate_trainability : Detect barren plateau risk.
"""

from __future__ import annotations

import logging
import warnings
from concurrent.futures import Executor, ProcessPoolExecutor, ThreadPoolExecutor
from typing import TYPE_CHECKING, Any, Literal, TypedDict, cast, overload

import numpy as np
from numpy.typing import NDArray
from scipy.special import rel_entr

from encoding_atlas.analysis._ci import percentile_bootstrap_ci, validate_ci_args
from encoding_atlas.analysis._parallel import ParallelArg, resolve_parallel_mode
from encoding_atlas.analysis._sampling import (
    SamplingMethod,
    generate_sample_batch,
    validate_sampling,
)
from encoding_atlas.analysis._utils import (
    compute_fidelity,
    create_rng,
    simulate_encoding_statevector,
    validate_encoding_for_analysis,
)
from encoding_atlas.core.exceptions import (
    AnalysisError,
    InsufficientSamplesError,
    NumericalInstabilityError,
    SimulationError,
)

if TYPE_CHECKING:
    from encoding_atlas.core.base import BaseEncoding

# =============================================================================
# Module-Level Logger
# =============================================================================

_logger = logging.getLogger(__name__)

# =============================================================================
# Public API
# =============================================================================

__all__ = [
    "compute_expressibility",
    "compute_fidelity_distribution",
    "compute_haar_distribution",
    "ExpressibilityResult",
]

# =============================================================================
# Type Definitions
# =============================================================================


class ExpressibilityResult(TypedDict):
    """Result dictionary from expressibility computation.

    This TypedDict defines the structure of the result returned by
    :func:`compute_expressibility` when ``return_distributions=True``.

    Attributes
    ----------
    expressibility : float
        Normalized expressibility score in [0, 1]. Higher values indicate
        the encoding's fidelity distribution is closer to Haar-random,
        meaning it can explore more of the Hilbert space.
    kl_divergence : float
        Raw Kullback-Leibler divergence from the encoding's fidelity
        distribution to the Haar distribution. Lower values indicate
        higher expressibility.
    fidelity_distribution : NDArray[np.floating]
        Histogram of sampled fidelities (probability for each bin).
        Shape: (n_bins,). Values sum to approximately 1.
    haar_distribution : NDArray[np.floating]
        Theoretical Haar-random fidelity distribution evaluated at
        the same bin centers. Shape: (n_bins,).
    bin_edges : NDArray[np.floating]
        Edges of the histogram bins. Shape: (n_bins + 1,).
        Range is [0, 1] for fidelity values.
    n_samples : int
        Number of fidelity samples used in the computation.
    n_bins : int
        Number of histogram bins used.
    convergence_estimate : float
        Bootstrap estimate of the standard error of the KL divergence.
        Smaller values indicate more reliable results.
    mean_fidelity : float
        Mean of the sampled fidelities. Useful for understanding
        the typical overlap between encoded states.
    std_fidelity : float
        Standard deviation of the sampled fidelities.
    expressibility_ci_lower : float
        Lower bound of the percentile bootstrap confidence interval on
        ``expressibility`` at ``confidence_level``. Computed by
        resampling the per-sample fidelity array and re-running the
        full histogram → KL → score pipeline on each resample.
    expressibility_ci_upper : float
        Upper bound of the percentile bootstrap CI on ``expressibility``.
    mean_fidelity_ci_lower : float
        Lower bound of the bootstrap CI on ``mean_fidelity``.
    mean_fidelity_ci_upper : float
        Upper bound of the bootstrap CI on ``mean_fidelity``.
    confidence_level : float
        Two-sided confidence level used for the CI bounds above
        (default 0.95 → 95% CIs).
    sampling : {'uniform', 'sobol'}
        Sampling strategy that produced the fidelity pairs. See
        :func:`compute_expressibility` for details.

    Examples
    --------
    >>> result = compute_expressibility(enc, return_distributions=True, seed=42)
    >>> print(f"Expressibility: {result['expressibility']:.4f}")
    >>> print(f"KL Divergence: {result['kl_divergence']:.4f}")
    >>> print(f"Mean Fidelity: {result['mean_fidelity']:.4f}")
    >>> lo, hi = result['expressibility_ci_lower'], result['expressibility_ci_upper']
    >>> print(f"95% CI: [{lo:.4f}, {hi:.4f}]")
    """

    expressibility: float
    kl_divergence: float
    fidelity_distribution: NDArray[np.floating[Any]]
    haar_distribution: NDArray[np.floating[Any]]
    bin_edges: NDArray[np.floating[Any]]
    n_samples: int
    n_bins: int
    convergence_estimate: float
    mean_fidelity: float
    std_fidelity: float
    expressibility_ci_lower: float
    expressibility_ci_upper: float
    mean_fidelity_ci_lower: float
    mean_fidelity_ci_upper: float
    confidence_level: float
    sampling: str


# =============================================================================
# Module-Level Constants
# =============================================================================

# Default number of samples for fidelity distribution estimation.
#
# RATIONALE: Expressibility requires MORE samples than other analysis metrics
# (entanglement uses 1000, trainability uses 500) because:
#
# 1. HISTOGRAM ESTIMATION: Expressibility is computed via KL divergence between
#    two histograms (sampled fidelities vs. Haar distribution). Histogram-based
#    estimators require O(n_bins²) samples for accurate bin counts.
#
# 2. SENSITIVITY TO SHAPE: KL divergence is sensitive to the tail of the
#    distribution. Insufficient samples lead to noisy tails and unreliable
#    KL estimates. With n_bins=75, we need ~67 samples per bin on average.
#
# 3. LITERATURE STANDARD: Published expressibility studies typically use
#    1000-10000 samples (Sim et al., 2019; Schuld et al., 2021).
#
# 4. COST: Each sample requires 2 circuit simulations (for the fidelity pair),
#    but no gradient computation, making samples relatively cheap.
#
# With 5000 samples and 75 bins, we achieve ~67 samples/bin, which provides
# statistically stable histogram estimation for most encodings.
_DEFAULT_N_SAMPLES: int = 5000

# Default number of histogram bins for fidelity distribution.
#
# RATIONALE: The number of bins balances resolution against statistical noise.
# Too few bins lose distribution shape; too many bins have noisy counts.
# Rule of thumb: n_bins ≈ √n_samples = √5000 ≈ 71, rounded to 75.
_DEFAULT_N_BINS: int = 75

# Minimum sample count below which results are unreliable (warning threshold).
# With 75 bins, 100 samples gives ~1.3 samples/bin, which is statistically
# marginal but may still provide rough estimates for quick exploration.
_MIN_SAMPLES_WARNING: int = 100

# Minimum sample count below which computation is refused (error threshold).
# Below 10 samples, histogram estimation is meaningless and KL divergence
# becomes numerically unstable due to empty bins.
_MIN_SAMPLES_ERROR: int = 10

# Maximum KL divergence for normalization
# Chosen to map typical KL divergence range to [0, 1]
# KL > 10 indicates extremely non-Haar distribution
_MAX_KL_DIVERGENCE: float = 10.0

# Small value to prevent numerical issues (log(0), division by zero)
# Chosen to be much smaller than typical probability values but
# larger than machine epsilon to avoid underflow
_NUMERICAL_EPSILON: float = 1e-10

# Default range for sampling input features
# [0, 2π] covers full rotation range for typical quantum gates
_DEFAULT_INPUT_RANGE: tuple[float, float] = (0.0, 2.0 * np.pi)

# Number of bootstrap samples for convergence estimation
_DEFAULT_N_BOOTSTRAP: int = 100

# Default number of bootstrap resamples for confidence-interval estimation.
# 200 is enough to stabilize the percentile endpoints to ~1% jitter without
# adding meaningful cost on top of the (much more expensive) simulation work.
_DEFAULT_N_BOOTSTRAP_CI: int = 200

# Default two-sided confidence level for reported CIs.
_DEFAULT_CONFIDENCE_LEVEL: float = 0.95

# Qubit threshold for performance warnings
_QUBIT_WARNING_THRESHOLD: int = 10


# =============================================================================
# Main Public Functions
# =============================================================================


@overload
def compute_expressibility(
    encoding: BaseEncoding,
    n_samples: int = ...,
    n_bins: int | None = ...,
    input_range: tuple[float, float] = ...,
    seed: int | None = ...,
    backend: Literal["pennylane", "qiskit", "cirq"] = ...,
    return_distributions: Literal[False] = ...,
    verbose: bool = ...,
    parallel: ParallelArg = ...,
    max_workers: int | None = ...,
    sampling: SamplingMethod = ...,
    confidence_level: float = ...,
    n_bootstrap_ci: int = ...,
) -> float: ...


@overload
def compute_expressibility(
    encoding: BaseEncoding,
    n_samples: int = ...,
    n_bins: int | None = ...,
    input_range: tuple[float, float] = ...,
    seed: int | None = ...,
    backend: Literal["pennylane", "qiskit", "cirq"] = ...,
    return_distributions: Literal[True] = ...,
    verbose: bool = ...,
    parallel: ParallelArg = ...,
    max_workers: int | None = ...,
    sampling: SamplingMethod = ...,
    confidence_level: float = ...,
    n_bootstrap_ci: int = ...,
) -> ExpressibilityResult: ...


def compute_expressibility(
    encoding: BaseEncoding,
    n_samples: int = _DEFAULT_N_SAMPLES,
    n_bins: int | None = None,
    input_range: tuple[float, float] = _DEFAULT_INPUT_RANGE,
    seed: int | None = None,
    backend: Literal["pennylane", "qiskit", "cirq"] = "pennylane",
    return_distributions: bool = False,
    verbose: bool = False,
    parallel: ParallelArg = False,
    max_workers: int | None = None,
    sampling: SamplingMethod = "uniform",
    confidence_level: float = _DEFAULT_CONFIDENCE_LEVEL,
    n_bootstrap_ci: int = _DEFAULT_N_BOOTSTRAP_CI,
) -> float | ExpressibilityResult:
    """Compute the expressibility of a quantum encoding.

    Expressibility quantifies how well the encoding can explore the Hilbert
    space compared to Haar-random states. Higher expressibility (closer to 1.0)
    indicates the encoding can generate a more diverse set of quantum states,
    which is generally desirable for variational quantum algorithms.

    The computation works by:

    1. Sampling random input pairs and computing their quantum states
    2. Computing fidelities between state pairs
    3. Building a histogram of fidelities
    4. Comparing to the theoretical Haar-random distribution via KL divergence
    5. Normalizing to a [0, 1] score

    Parameters
    ----------
    encoding : BaseEncoding
        The encoding instance to analyze. Must have ``n_features`` and
        ``n_qubits`` attributes and implement ``get_circuit()``.
    n_samples : int, default=5000
        Number of random input pairs to sample. Higher values give more
        accurate results but increase computation time. A minimum of 1000
        samples is recommended for reliable results.
    n_bins : int or None, default=None
        Number of bins for the fidelity histogram. If None (default),
        automatically set to ``min(75, n_samples)`` so that small sample
        counts don't require manually tuning the bin count. If provided
        explicitly, must satisfy ``10 ≤ n_bins ≤ n_samples``.
        Rule of thumb: n_bins ≈ √n_samples.
    input_range : tuple[float, float], default=(0, 2π)
        Range for sampling random input values. The default covers the
        full rotation range for typical quantum gates.
    seed : int, optional
        Random seed for reproducibility. If None, results will vary
        between runs. Always specify a seed for reproducible analysis.
    backend : {"pennylane", "qiskit", "cirq"}, default="pennylane"
        Backend to use for circuit simulation.

        - ``"pennylane"``: Uses PennyLane's default.qubit simulator (recommended)
        - ``"qiskit"``: Uses Qiskit's Statevector class
        - ``"cirq"``: Uses Cirq's Simulator for statevector simulation
    return_distributions : bool, default=False
        If True, return full result dictionary including fidelity
        distributions, bin edges, and statistics.
        If False, return only the expressibility score (float).
    verbose : bool, default=False
        If True, log progress information during computation.
    parallel : bool or {'thread', 'process'}, default=False
        Parallel-dispatch mode for the per-sample fidelity computation.
        Each sample requires two independent statevector simulations,
        making the loop embarrassingly parallel.

        - ``False`` (default) — sequential, no executor overhead.
        - ``True`` or ``'thread'`` — :class:`ThreadPoolExecutor`. Useful
          when the backend simulator releases the GIL during numerical
          work (NumPy operations typically do).
        - ``'process'`` — :class:`ProcessPoolExecutor` for true CPU
          parallelism. The encoding is pickled once per worker. Best
          for large ``n_samples`` and CPU-bound backends. Has
          process-startup overhead, so only worthwhile for batches of
          roughly 100+ samples. Workers exchange only NumPy arrays /
          floats, so process-pool parallelism works with **all** three
          backends here (unlike ``BaseEncoding.get_circuits`` where
          PennyLane's local-closure qfuncs prevent process-pool use).

        Output is numerically identical across all modes for a fixed
        ``seed``: the RNG is fully consumed in the main process before
        any work is dispatched to workers.
    max_workers : int or None, default=None
        Maximum number of workers when ``parallel`` is enabled.
        ``None`` defers to the executor's default (typically based on
        CPU count).
    sampling : {'uniform', 'sobol'}, default='uniform'
        Strategy for drawing the random input pairs ``(X1, X2)``:

        - ``'uniform'`` (default, unchanged behavior): pseudo-random
          i.i.d. samples via :meth:`numpy.random.Generator.uniform`.
        - ``'sobol'``: Sobol' low-discrepancy quasi-random sequence
          via :class:`scipy.stats.qmc.Sobol`. Covers the hypercube
          much more evenly than i.i.d. uniform draws and typically
          reaches the same KL accuracy with **30-50% fewer samples**.
          For best statistical properties round ``n_samples`` up to
          the nearest power of two.

        Sobol is seeded from the same ``seed`` argument so a given
        ``(seed, sampling)`` pair is fully reproducible.
    confidence_level : float, default=0.95
        Two-sided confidence level for the bootstrap CIs reported in
        the result dict (only used when ``return_distributions=True``).
        Must lie strictly in ``(0, 1)``. Common choices: 0.90, 0.95,
        0.99.
    n_bootstrap_ci : int, default=200
        Number of bootstrap resamples used to estimate the
        ``expressibility`` and ``mean_fidelity`` percentile CIs
        (only when ``return_distributions=True``). 200 stabilizes
        the percentile endpoints to ~1% jitter; raise to ~1000 for
        publication-grade precision.

    Returns
    -------
    float or ExpressibilityResult
        If ``return_distributions=False``: Expressibility score in [0, 1].
        Higher values indicate more expressive encodings.

        If ``return_distributions=True``: Dictionary containing:

        - **expressibility**: float in [0, 1], higher = more expressive
        - **kl_divergence**: raw KL divergence value
        - **fidelity_distribution**: sampled fidelity histogram
        - **haar_distribution**: theoretical Haar distribution
        - **bin_edges**: histogram bin edges
        - **n_samples**: number of samples used
        - **n_bins**: number of histogram bins
        - **convergence_estimate**: bootstrap standard error estimate
        - **mean_fidelity**: mean of sampled fidelities
        - **std_fidelity**: standard deviation of sampled fidelities

    Raises
    ------
    InsufficientSamplesError
        If ``n_samples < 10`` (too few for meaningful statistics).
    SimulationError
        If circuit simulation fails for the given backend.
    AnalysisError
        If encoding is invalid or computation fails.
    ValueError
        If explicit ``n_bins < 10`` or ``n_bins > n_samples``, or if
        ``input_range[0] >= input_range[1]``.

    Warns
    -----
    UserWarning
        If ``n_samples < 100`` (results may be unreliable).
    UserWarning
        If encoding has > 10 qubits (computation may be slow).

    Examples
    --------
    Basic usage with default parameters:

    >>> from encoding_atlas import AngleEncoding
    >>> enc = AngleEncoding(n_features=4)
    >>> expr = compute_expressibility(enc, seed=42)
    >>> print(f"Expressibility: {expr:.4f}")
    Expressibility: ...

    Get full result with distributions:

    >>> result = compute_expressibility(enc, return_distributions=True, seed=42)
    >>> print(f"KL Divergence: {result['kl_divergence']:.4f}")
    >>> print(f"Samples used: {result['n_samples']}")

    Compare two encodings:

    >>> from encoding_atlas import IQPEncoding
    >>> enc1 = AngleEncoding(n_features=4)  # Non-entangling
    >>> enc2 = IQPEncoding(n_features=4, reps=2)  # Entangling
    >>> expr1 = compute_expressibility(enc1, n_samples=1000, seed=42)
    >>> expr2 = compute_expressibility(enc2, n_samples=1000, seed=42)
    >>> print(f"AngleEncoding: {expr1:.4f}")
    >>> print(f"IQPEncoding: {expr2:.4f}")
    >>> # IQP typically shows higher expressibility due to entanglement

    Notes
    -----
    **Computational Complexity**

    The complexity is O(n_samples × simulation_cost), where simulation_cost
    scales as O(2^n_qubits). For encodings with more than 10 qubits,
    consider reducing n_samples or using approximate methods.

    **Interpretation**

    - Expressibility ≈ 0: Encoding produces states in a narrow region
      of Hilbert space (e.g., product states only)
    - Expressibility ≈ 1: Encoding produces states distributed like
      Haar-random states (explores full Hilbert space)

    **Normalization Formula**

    The expressibility score is normalized from KL divergence using::

        expr = 1.0 - min(1.0, kl_divergence / MAX_KL)

    This maps KL divergence to [0, 1] where higher values indicate
    distributions closer to Haar-random (more expressive).

    **Statistical Reliability**

    The ``convergence_estimate`` in the result dictionary provides a
    bootstrap estimate of the standard error. Values < 0.05 generally
    indicate reliable results.

    See Also
    --------
    compute_fidelity_distribution : Compute fidelity distribution only.
    compute_haar_distribution : Compute theoretical Haar distribution.
    compute_entanglement_capability : Related metric for entanglement.

    References
    ----------
    .. [1] Sim, S., Johnson, P. D., & Aspuru-Guzik, A. (2019).
           "Expressibility and entangling capability of parameterized
           quantum circuits for hybrid quantum-classical algorithms."
           Advanced Quantum Technologies, 2(12), 1900070.
    """
    # =========================================================================
    # Input Validation
    # =========================================================================

    # Validate encoding
    validate_encoding_for_analysis(encoding)

    # Validate n_samples
    if not isinstance(n_samples, int) or n_samples < 1:
        raise ValueError(f"n_samples must be a positive integer, got {n_samples}")

    if n_samples < _MIN_SAMPLES_ERROR:
        raise InsufficientSamplesError(
            f"n_samples must be at least {_MIN_SAMPLES_ERROR} for meaningful "
            f"statistics, got {n_samples}. Recommended minimum: "
            f"{_MIN_SAMPLES_WARNING}.",
            requested_samples=n_samples,
            minimum_samples=_MIN_SAMPLES_ERROR,
            metric="expressibility",
        )

    if n_samples < _MIN_SAMPLES_WARNING:
        warnings.warn(
            f"n_samples={n_samples} is low; results may be unreliable. "
            f"Recommended minimum: {_MIN_SAMPLES_WARNING}.",
            UserWarning,
            stacklevel=2,
        )

    # Resolve n_bins: auto-select when not specified, validate when explicit
    if n_bins is None:
        # Auto-select: use the default, clamped to n_samples so that users
        # who simply pass a small n_samples don't hit an unexpected error.
        n_bins = min(_DEFAULT_N_BINS, n_samples)
    else:
        # User explicitly provided n_bins — validate strictly
        if not isinstance(n_bins, int) or n_bins < 1:
            raise ValueError(f"n_bins must be a positive integer, got {n_bins}")

        if n_bins < 10:
            raise ValueError(
                f"n_bins must be at least 10 for meaningful histogram, got {n_bins}"
            )

        if n_bins > n_samples:
            raise ValueError(
                f"n_bins ({n_bins}) cannot exceed n_samples ({n_samples}). "
                f"Reduce n_bins or increase n_samples."
            )

    # Validate input_range
    if len(input_range) != 2:
        raise ValueError(f"input_range must have 2 elements, got {len(input_range)}")

    if input_range[0] >= input_range[1]:
        raise ValueError(
            f"input_range[0] must be less than input_range[1], "
            f"got [{input_range[0]}, {input_range[1]}]"
        )

    # Validate parallel argument early so a bad value surfaces as a clean
    # ``ValueError`` instead of being wrapped in ``AnalysisError`` by the
    # broad ``except`` around the sampling loop below.
    resolve_parallel_mode(parallel)

    # Validate sampling/CI arguments upfront for the same reason — bad
    # values must surface as plain ValueErrors before any expensive work.
    validate_sampling(sampling)
    validate_ci_args(confidence_level, n_bootstrap_ci)

    # Warn about large qubit counts
    n_qubits = encoding.n_qubits
    if n_qubits > _QUBIT_WARNING_THRESHOLD:
        warnings.warn(
            f"Encoding has {n_qubits} qubits. Computation may be slow due "
            f"to exponential scaling of simulation. Consider using fewer "
            f"samples or a smaller encoding for testing.",
            UserWarning,
            stacklevel=2,
        )

    # Validate backend
    if backend not in ("pennylane", "qiskit", "cirq"):
        raise ValueError(
            f"backend must be 'pennylane', 'qiskit', or 'cirq', got {backend!r}"
        )

    # =========================================================================
    # Setup
    # =========================================================================

    rng = create_rng(seed)
    n_features = encoding.n_features

    if verbose:
        _logger.info(
            "Computing expressibility for %s (n_qubits=%d, n_features=%d, "
            "n_samples=%d, n_bins=%d)",
            encoding.__class__.__name__,
            n_qubits,
            n_features,
            n_samples,
            n_bins,
        )

    # =========================================================================
    # Sample Fidelities
    # =========================================================================

    try:
        fidelities = _sample_fidelities(
            encoding=encoding,
            n_samples=n_samples,
            n_features=n_features,
            input_range=input_range,
            rng=rng,
            backend=backend,
            verbose=verbose,
            parallel=parallel,
            max_workers=max_workers,
            sampling=sampling,
        )
    except SimulationError:
        raise
    except Exception as e:
        raise AnalysisError(
            f"Failed to sample fidelities for {encoding.__class__.__name__}: {e}",
            details={"error_type": type(e).__name__, "error_message": str(e)},
        ) from e

    # =========================================================================
    # Build Histogram
    # =========================================================================

    # Fidelity is in [0, 1], use fixed bins for consistency
    # density=True normalizes so that integral over bins equals 1
    hist_encoding, bin_edges = np.histogram(
        fidelities,
        bins=n_bins,
        range=(0.0, 1.0),
        density=True,
    )

    # Convert density to probability mass function
    # For uniform bins: P_i = density_i × bin_width
    bin_width = bin_edges[1] - bin_edges[0]
    P_encoding = hist_encoding * bin_width

    # Ensure proper normalization (should already sum to ~1)
    P_encoding_sum = P_encoding.sum()
    if P_encoding_sum > _NUMERICAL_EPSILON:
        P_encoding = P_encoding / P_encoding_sum
    else:
        # Degenerate case: fidelity distribution has near-zero total probability mass.
        # This can occur when:
        # 1. All fidelities are concentrated in a single bin (encoding produces
        #    nearly identical states for all inputs)
        # 2. Numerical underflow in histogram computation
        # 3. Very few unique fidelity values that don't span the histogram range
        #
        # We fall back to a uniform distribution to ensure KL divergence computation
        # remains numerically stable. This is a conservative choice that will result
        # in a meaningful (though potentially less accurate) expressibility estimate.
        _logger.warning(
            "Fidelity distribution is degenerate (sum=%.2e). This may indicate the "
            "encoding produces nearly identical states for all inputs, or numerical "
            "issues in histogram computation. Falling back to uniform distribution "
            "for KL divergence computation. Consider increasing n_samples or "
            "checking the encoding's behavior.",
            P_encoding_sum,
        )
        P_encoding = np.ones(n_bins, dtype=np.float64) / n_bins

    # =========================================================================
    # Compute Haar Distribution
    # =========================================================================

    # Evaluate at bin centers for comparison
    bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2.0
    P_haar = compute_haar_distribution(n_qubits, bin_centers)

    # =========================================================================
    # Compute KL Divergence
    # =========================================================================

    # Add epsilon to prevent log(0) and handle zero probabilities
    P_encoding_safe = P_encoding + _NUMERICAL_EPSILON
    P_haar_safe = P_haar + _NUMERICAL_EPSILON

    # Renormalize after adding epsilon
    P_encoding_safe = P_encoding_safe / P_encoding_safe.sum()
    P_haar_safe = P_haar_safe / P_haar_safe.sum()

    # Compute KL(P_encoding || P_haar) using scipy's rel_entr
    # rel_entr(p, q) = p * log(p/q) with proper handling of zeros
    kl_divergence_array = rel_entr(P_encoding_safe, P_haar_safe)

    # Check for numerical issues
    if np.any(np.isnan(kl_divergence_array)) or np.any(np.isinf(kl_divergence_array)):
        raise NumericalInstabilityError(
            "KL divergence computation produced NaN or Inf values. "
            "This may indicate numerical instability in the distribution.",
            operation="compute_kl_divergence",
            details={
                "has_nan": bool(np.any(np.isnan(kl_divergence_array))),
                "has_inf": bool(np.any(np.isinf(kl_divergence_array))),
            },
        )

    kl_divergence = float(np.sum(kl_divergence_array))

    # Ensure non-negative (can be slightly negative due to numerical error)
    if kl_divergence < 0:
        if kl_divergence < -_NUMERICAL_EPSILON:
            _logger.warning(
                "KL divergence is negative (%.6e), clamping to 0", kl_divergence
            )
        kl_divergence = 0.0

    # =========================================================================
    # Normalize to Expressibility Score
    # =========================================================================

    # Lower KL = more expressive, so we invert and normalize
    # expressibility = 1 - min(1, KL/MAX_KL)
    expressibility = 1.0 - min(1.0, kl_divergence / _MAX_KL_DIVERGENCE)

    # Clamp to [0, 1] for safety
    expressibility = float(np.clip(expressibility, 0.0, 1.0))

    # =========================================================================
    # Estimate Convergence / Statistical Error
    # =========================================================================

    convergence_estimate = _estimate_convergence(
        fidelities=fidelities,
        n_bins=n_bins,
        n_qubits=n_qubits,
        rng=rng,
        n_bootstrap=_DEFAULT_N_BOOTSTRAP,
    )

    # =========================================================================
    # Compute Additional Statistics
    # =========================================================================

    mean_fidelity = float(np.mean(fidelities))
    std_fidelity = float(np.std(fidelities, ddof=1))

    if verbose:
        _logger.info(
            "Expressibility: %.4f (KL=%.4f, mean_fid=%.4f, convergence=%.4f)",
            expressibility,
            kl_divergence,
            mean_fidelity,
            convergence_estimate,
        )

    # =========================================================================
    # Bootstrap Confidence Intervals (only for the detailed result)
    # =========================================================================
    #
    # The CI cost is bounded by ``n_bootstrap_ci`` × histogram-pipeline-cost,
    # which is negligible next to the ``n_samples`` simulations we already
    # paid for above. We only compute them when the caller asked for the
    # detailed result; the float-only return path stays fast.

    if return_distributions:
        expressibility_ci = _bootstrap_expressibility_ci(
            fidelities=fidelities,
            n_bins=n_bins,
            n_qubits=n_qubits,
            rng=rng,
            n_bootstrap=n_bootstrap_ci,
            confidence_level=confidence_level,
        )
        mean_fidelity_ci = percentile_bootstrap_ci(
            samples=fidelities,
            statistic_fn=np.mean,
            rng=rng,
            n_bootstrap=n_bootstrap_ci,
            confidence_level=confidence_level,
        )

    # =========================================================================
    # Return Results
    # =========================================================================

    if return_distributions:
        return ExpressibilityResult(
            expressibility=expressibility,
            kl_divergence=kl_divergence,
            fidelity_distribution=P_encoding.astype(np.float64),
            haar_distribution=P_haar.astype(np.float64),
            bin_edges=bin_edges.astype(np.float64),
            n_samples=n_samples,
            n_bins=n_bins,
            convergence_estimate=convergence_estimate,
            mean_fidelity=mean_fidelity,
            std_fidelity=std_fidelity,
            expressibility_ci_lower=expressibility_ci[0],
            expressibility_ci_upper=expressibility_ci[1],
            mean_fidelity_ci_lower=mean_fidelity_ci[0],
            mean_fidelity_ci_upper=mean_fidelity_ci[1],
            confidence_level=float(confidence_level),
            sampling=str(sampling),
        )

    return expressibility


def compute_fidelity_distribution(
    encoding: BaseEncoding,
    n_samples: int = _DEFAULT_N_SAMPLES,
    input_range: tuple[float, float] = _DEFAULT_INPUT_RANGE,
    seed: int | None = None,
    backend: Literal["pennylane", "qiskit", "cirq"] = "pennylane",
    parallel: ParallelArg = False,
    max_workers: int | None = None,
    sampling: SamplingMethod = "uniform",
) -> NDArray[np.floating[Any]]:
    """Compute the fidelity distribution for an encoding.

    Samples random input pairs and computes the fidelity between their
    corresponding quantum states. This is useful for analyzing the
    encoding's behavior without computing the full expressibility.

    Parameters
    ----------
    encoding : BaseEncoding
        The encoding to analyze.
    n_samples : int, default=5000
        Number of random input pairs to sample.
    input_range : tuple[float, float], default=(0, 2π)
        Range for random input sampling.
    seed : int, optional
        Random seed for reproducibility.
    backend : {"pennylane", "qiskit", "cirq"}, default="pennylane"
        Backend for circuit simulation.

        - ``"pennylane"``: Uses PennyLane's default.qubit simulator (recommended)
        - ``"qiskit"``: Uses Qiskit's Statevector class
        - ``"cirq"``: Uses Cirq's Simulator for statevector simulation
    parallel : bool or {'thread', 'process'}, default=False
        Parallel-dispatch mode for the per-sample fidelity computation.
        See :func:`compute_expressibility` for the full discussion.
    max_workers : int or None, default=None
        Maximum number of workers when ``parallel`` is enabled.
    sampling : {'uniform', 'sobol'}, default='uniform'
        Strategy for drawing the random input pairs. See
        :func:`compute_expressibility` for the full discussion.

    Returns
    -------
    NDArray[np.floating]
        Array of fidelity values, shape ``(n_samples,)``, each in [0, 1].

    Raises
    ------
    InsufficientSamplesError
        If ``n_samples < 10``.
    SimulationError
        If circuit simulation fails.
    AnalysisError
        If encoding is invalid.

    Examples
    --------
    >>> from encoding_atlas import IQPEncoding
    >>> enc = IQPEncoding(n_features=4, reps=1)
    >>> fidelities = compute_fidelity_distribution(enc, n_samples=1000, seed=42)
    >>> print(f"Mean fidelity: {fidelities.mean():.4f}")
    >>> print(f"Std fidelity: {fidelities.std():.4f}")

    Notes
    -----
    The fidelity F = |⟨ψ₁|ψ₂⟩|² measures the overlap between two quantum
    states. F = 1 means identical states (up to global phase), F = 0 means
    orthogonal states.

    For Haar-random states in high dimensions, most pairs have F ≈ 0
    because random high-dimensional vectors are typically nearly orthogonal.

    See Also
    --------
    compute_expressibility : Full expressibility computation.
    compute_haar_distribution : Theoretical Haar distribution.
    """
    # Validate inputs
    validate_encoding_for_analysis(encoding)

    if not isinstance(n_samples, int) or n_samples < 1:
        raise ValueError(f"n_samples must be a positive integer, got {n_samples}")

    if n_samples < _MIN_SAMPLES_ERROR:
        raise InsufficientSamplesError(
            f"n_samples must be at least {_MIN_SAMPLES_ERROR}, got {n_samples}",
            requested_samples=n_samples,
            minimum_samples=_MIN_SAMPLES_ERROR,
            metric="fidelity_distribution",
        )

    if len(input_range) != 2 or input_range[0] >= input_range[1]:
        raise ValueError(
            f"input_range must be (min, max) with min < max, got {input_range}"
        )

    if backend not in ("pennylane", "qiskit", "cirq"):
        raise ValueError(
            f"backend must be 'pennylane', 'qiskit', or 'cirq', got {backend!r}"
        )

    # Validate parallel + sampling arguments upfront for clean ValueErrors.
    resolve_parallel_mode(parallel)
    validate_sampling(sampling)

    # Setup and sample
    rng = create_rng(seed)
    n_features = encoding.n_features

    return _sample_fidelities(
        encoding=encoding,
        n_samples=n_samples,
        n_features=n_features,
        input_range=input_range,
        rng=rng,
        backend=backend,
        verbose=False,
        parallel=parallel,
        max_workers=max_workers,
        sampling=sampling,
    )


def compute_haar_distribution(
    n_qubits: int,
    fidelity_values: NDArray[np.floating[Any]],
) -> NDArray[np.floating[Any]]:
    """Compute the Haar-random fidelity distribution.

    For a d-dimensional Hilbert space (d = 2^n_qubits), the probability
    density of fidelities between Haar-random states is:

        P_Haar(F) = (d - 1)(1 - F)^(d - 2)

    This is derived from the fact that Haar-random states are uniformly
    distributed on the complex unit sphere.

    Parameters
    ----------
    n_qubits : int
        Number of qubits (determines Hilbert space dimension d = 2^n_qubits).
    fidelity_values : NDArray[np.floating]
        Array of fidelity values at which to evaluate the distribution.
        Should be in [0, 1].

    Returns
    -------
    NDArray[np.floating]
        Probability density values at each fidelity point, normalized
        to sum to 1 (assuming fidelity_values are evenly spaced bin centers).

    Raises
    ------
    ValueError
        If ``n_qubits < 1``.

    Examples
    --------
    >>> import numpy as np
    >>> fidelities = np.linspace(0, 1, 100)
    >>> P_haar = compute_haar_distribution(n_qubits=4, fidelity_values=fidelities)
    >>> print(f"P_Haar shape: {P_haar.shape}")
    >>> print(f"P_Haar sum: {P_haar.sum():.4f}")  # Should be close to 1

    Notes
    -----
    **Physical Interpretation**

    The Haar distribution represents what we would observe if we picked
    two states uniformly at random from the Hilbert space. For large d:

    - Most pairs have very low fidelity (nearly orthogonal)
    - High fidelity pairs are exponentially rare
    - The distribution is concentrated near F = 0

    **Numerical Considerations**

    For large d (many qubits), the term (1-F)^(d-2) can cause underflow.
    We use log-space computation for d > 100 to maintain numerical stability.

    **Single Qubit Special Case**

    For d = 2 (single qubit), P_Haar(F) = 1 (uniform distribution),
    because the Bloch sphere has special geometry where all fidelities
    are equally likely.

    References
    ----------
    .. [1] Życzkowski, K., & Sommers, H.-J. (2001).
           "Induced measures in the space of mixed quantum states."
           Journal of Physics A, 34(35), 7111.
    """
    # Validate n_qubits
    if not isinstance(n_qubits, int) or n_qubits < 1:
        raise ValueError(f"n_qubits must be a positive integer, got {n_qubits}")

    # Convert to numpy array and ensure float type
    F = np.asarray(fidelity_values, dtype=np.float64)

    # Handle empty input gracefully (regardless of code path)
    if F.size == 0:
        return np.array([], dtype=np.float64)

    # Hilbert space dimension
    d = 2**n_qubits

    # Special case: single qubit (d=2)
    # P_Haar(F) = (2-1)(1-F)^(2-2) = 1 × (1-F)^0 = 1
    # Fidelity is uniformly distributed on [0, 1]
    if d == 2:
        P_haar = np.ones_like(F, dtype=np.float64)
        # Normalize
        P_haar = P_haar / (P_haar.sum() + _NUMERICAL_EPSILON)
        normalized: NDArray[np.floating[Any]] = P_haar
        return normalized

    # General case: P_Haar(F) = (d - 1)(1 - F)^(d - 2)
    # Clip (1-F) to avoid numerical issues at F=1
    one_minus_F = np.clip(1.0 - F, _NUMERICAL_EPSILON, 1.0)

    # For large d, use log-space computation to prevent overflow/underflow
    # log(P) = log(d-1) + (d-2)*log(1-F)
    if d > 100:
        log_P = np.log(d - 1) + (d - 2) * np.log(one_minus_F)
        # Subtract max for numerical stability before exp
        log_P_max: np.floating[Any] = np.max(log_P)
        P_haar = np.exp(log_P - log_P_max)
    else:
        # Direct computation for smaller d
        P_haar = (d - 1) * np.power(one_minus_F, d - 2)

    # Handle any potential NaN or Inf from computation
    P_haar = np.nan_to_num(P_haar, nan=0.0, posinf=0.0, neginf=0.0)

    # Normalize to probability distribution
    P_sum = P_haar.sum()
    if P_sum > _NUMERICAL_EPSILON:
        P_haar = P_haar / P_sum
    else:
        # Degenerate case - uniform fallback
        # This can occur due to numerical underflow when:
        # 1. n_qubits is large (d is very large, causing (1-F)^(d-2) to underflow)
        # 2. All fidelity values are very close to 1 (making (1-F) ≈ 0)
        # 3. Numerical precision issues in the log-space computation
        _logger.warning(
            "Haar distribution sum is near zero (sum=%.2e) for n_qubits=%d (d=%d). "
            "Falling back to uniform distribution. This may indicate numerical "
            "instability due to large Hilbert space dimension or fidelity values "
            "concentrated near 1.0. Consider using fewer qubits or checking input data.",
            P_sum,
            n_qubits,
            d,
        )
        P_haar = np.ones_like(P_haar) / len(P_haar)

    return cast("NDArray[np.floating[Any]]", P_haar.astype(np.float64))


# =============================================================================
# Private Helper Functions
# =============================================================================


# ---------------------------------------------------------------------------
# Process-pool worker plumbing (top-level for picklability)
# ---------------------------------------------------------------------------
#
# These globals are populated *once per worker process* by
# ``_fidelity_worker_init`` (registered as the executor's ``initializer``)
# so that the encoding instance and backend label are pickled across the
# wire just once per worker, not once per sample. The same pattern is used
# in :mod:`encoding_atlas.core.base` and proven safe there.

_FID_WORKER_ENCODING: BaseEncoding | None = None
_FID_WORKER_BACKEND: str | None = None


def _fidelity_worker_init(encoding: BaseEncoding, backend: str) -> None:
    """ProcessPoolExecutor initializer — runs once per worker process."""
    global _FID_WORKER_ENCODING, _FID_WORKER_BACKEND
    _FID_WORKER_ENCODING = encoding
    _FID_WORKER_BACKEND = backend


def _fidelity_worker_compute(
    pair: tuple[NDArray[np.floating[Any]], NDArray[np.floating[Any]]],
) -> float:
    """Worker entrypoint: compute one fidelity from an (x1, x2) pair."""
    assert (
        _FID_WORKER_ENCODING is not None and _FID_WORKER_BACKEND is not None
    ), "Process pool worker invoked before initializer ran"
    return _compute_one_fidelity(_FID_WORKER_ENCODING, pair, _FID_WORKER_BACKEND)


def _compute_one_fidelity(
    encoding: BaseEncoding,
    pair: tuple[NDArray[np.floating[Any]], NDArray[np.floating[Any]]],
    backend: str,
) -> float:
    """Simulate both inputs and return the clamped fidelity.

    Shared by the sequential, thread-pool, and process-pool code paths so
    they always produce identical floats for the same inputs.
    """
    x1, x2 = pair
    state1 = simulate_encoding_statevector(
        encoding, x1, backend=cast("Literal['pennylane', 'qiskit', 'cirq']", backend)
    )
    state2 = simulate_encoding_statevector(
        encoding, x2, backend=cast("Literal['pennylane', 'qiskit', 'cirq']", backend)
    )
    return float(np.clip(compute_fidelity(state1, state2), 0.0, 1.0))


def _sample_fidelities(
    encoding: BaseEncoding,
    n_samples: int,
    n_features: int,
    input_range: tuple[float, float],
    rng: np.random.Generator,
    backend: str,
    verbose: bool,
    parallel: ParallelArg = False,
    max_workers: int | None = None,
    sampling: SamplingMethod = "uniform",
) -> NDArray[np.floating[Any]]:
    """Sample fidelities between random input pairs.

    Generates random input pairs in batch, simulates encoding circuits,
    and computes fidelities. RNG calls are vectorized into single batch
    operations for reduced overhead.

    Parameters
    ----------
    encoding : BaseEncoding
        The encoding to analyze.
    n_samples : int
        Number of fidelity samples to generate.
    n_features : int
        Number of features in the encoding.
    input_range : tuple[float, float]
        (min, max) range for random input sampling.
    rng : np.random.Generator
        Random number generator for reproducibility.
    backend : str
        Backend for circuit simulation.
    verbose : bool
        If True, log progress.
    parallel : bool or {'thread', 'process'}, default=False
        Parallel-dispatch mode for the per-sample simulation. See
        :func:`compute_expressibility` for details.
    max_workers : int or None, default=None
        Maximum number of workers when ``parallel`` is enabled.

    Returns
    -------
    NDArray[np.floating]
        Array of fidelity values, shape ``(n_samples,)``. The numerical
        output is identical across ``parallel`` modes for a fixed
        ``rng`` — the RNG is fully consumed up front in the main
        process before any work is dispatched.

    Raises
    ------
    SimulationError
        If circuit simulation fails for any sample.
    """
    # Batch RNG generation — single call per input set. Pre-generating
    # the entire (X1, X2) batch in the main process means workers do no
    # RNG work, so the output is bit-identical across sequential /
    # thread / process modes for the same seeded ``rng``. The
    # ``sampling`` selector picks between i.i.d. uniform and
    # quasi-random Sobol' draws; both are seeded from the same ``rng``.
    X1 = generate_sample_batch(n_samples, n_features, input_range, rng, sampling)
    X2 = generate_sample_batch(n_samples, n_features, input_range, rng, sampling)

    mode = resolve_parallel_mode(parallel)

    # Sequential fast path. Also used when there's only one sample (where
    # an executor is pure overhead) and for thread mode of trivial sizes.
    if mode == "sequential" or n_samples <= 1:
        return _sample_fidelities_sequential(
            encoding, X1, X2, backend, verbose, n_samples
        )

    pairs = list(zip(X1, X2))

    # Declared up front so both pool branches share one narrowed type.
    executor: Executor
    if mode == "thread":
        # ThreadPoolExecutor shares memory; we close over ``encoding`` and
        # ``backend`` directly via the small worker callable below.
        def _one(pair: Any) -> float:
            return _compute_one_fidelity(encoding, pair, backend)

        try:
            with ThreadPoolExecutor(max_workers=max_workers) as executor:
                fidelities = np.fromiter(
                    executor.map(_one, pairs),
                    dtype=np.float64,
                    count=n_samples,
                )
        except SimulationError:
            raise
        except Exception as e:
            raise SimulationError(
                f"Failed to compute fidelities in thread pool: {e}",
                backend=backend,
                details={
                    "error_type": type(e).__name__,
                    "error_message": str(e),
                    "parallel": "thread",
                },
            ) from e
        return fidelities

    # mode == "process"
    # ProcessPoolExecutor pickles arguments per task; the
    # initializer/initargs pattern pickles the encoding once per worker
    # rather than once per sample.
    try:
        with ProcessPoolExecutor(
            max_workers=max_workers,
            initializer=_fidelity_worker_init,
            initargs=(encoding, backend),
        ) as executor:
            fidelities = np.fromiter(
                executor.map(_fidelity_worker_compute, pairs),
                dtype=np.float64,
                count=n_samples,
            )
    except SimulationError:
        raise
    except Exception as e:
        raise SimulationError(
            f"Failed to compute fidelities in process pool: {e}",
            backend=backend,
            details={
                "error_type": type(e).__name__,
                "error_message": str(e),
                "parallel": "process",
            },
        ) from e
    return fidelities


def _sample_fidelities_sequential(
    encoding: BaseEncoding,
    X1: NDArray[np.floating[Any]],
    X2: NDArray[np.floating[Any]],
    backend: str,
    verbose: bool,
    n_samples: int,
) -> NDArray[np.floating[Any]]:
    """Sequential implementation kept separate so the parallel branch in
    :func:`_sample_fidelities` stays linear-flow and easy to read."""
    fidelities: NDArray[np.float64] = np.zeros(n_samples, dtype=np.float64)
    log_interval = max(1, n_samples // 10)

    for i in range(n_samples):
        try:
            fidelities[i] = _compute_one_fidelity(encoding, (X1[i], X2[i]), backend)
        except SimulationError:
            raise
        except Exception as e:
            raise SimulationError(
                f"Failed to compute fidelity at sample {i}/{n_samples}: {e}",
                backend=backend,
                details={
                    "sample_index": i,
                    "error_type": type(e).__name__,
                    "error_message": str(e),
                },
            ) from e

        if verbose and (i + 1) % log_interval == 0:
            _logger.debug(
                "Sampled %d/%d fidelities (%.1f%%)",
                i + 1,
                n_samples,
                100.0 * (i + 1) / n_samples,
            )

    return fidelities


def _estimate_convergence(
    fidelities: NDArray[np.floating[Any]],
    n_bins: int,
    n_qubits: int,
    rng: np.random.Generator,
    n_bootstrap: int = _DEFAULT_N_BOOTSTRAP,
) -> float:
    """Estimate statistical convergence via bootstrap resampling.

    Performs bootstrap resampling to estimate the standard error of the
    KL divergence estimate. This provides a measure of how much the
    expressibility value would change with different random samples.

    Parameters
    ----------
    fidelities : NDArray[np.floating]
        Sampled fidelity values.
    n_bins : int
        Number of histogram bins.
    n_qubits : int
        Number of qubits (for Haar distribution).
    rng : np.random.Generator
        Random number generator.
    n_bootstrap : int
        Number of bootstrap samples.

    Returns
    -------
    float
        Standard error estimate for the KL divergence.
        Smaller values indicate more stable/reliable results.
    """
    n_samples = len(fidelities)

    # Quick return if too few samples for meaningful bootstrap
    if n_samples < 20:
        return float("inf")

    bootstrap_kls: NDArray[np.float64] = np.zeros(n_bootstrap, dtype=np.float64)

    # Pre-compute Haar distribution (same for all bootstrap samples)
    bin_edges = np.linspace(0.0, 1.0, n_bins + 1)
    bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2.0
    P_haar = compute_haar_distribution(n_qubits, bin_centers)
    P_haar_safe = P_haar + _NUMERICAL_EPSILON
    P_haar_safe = P_haar_safe / P_haar_safe.sum()

    bin_width = bin_edges[1] - bin_edges[0]

    for b in range(n_bootstrap):
        # Resample with replacement
        boot_indices = rng.choice(n_samples, size=n_samples, replace=True)
        boot_fidelities = fidelities[boot_indices]

        # Compute histogram for bootstrap sample
        hist, _ = np.histogram(
            boot_fidelities,
            bins=n_bins,
            range=(0.0, 1.0),
            density=True,
        )

        # Convert to probability mass
        P_boot = hist * bin_width
        P_boot_sum = P_boot.sum()
        if P_boot_sum > _NUMERICAL_EPSILON:
            P_boot = P_boot / P_boot_sum

        # Add epsilon and renormalize
        P_boot_safe = P_boot + _NUMERICAL_EPSILON
        P_boot_safe = P_boot_safe / P_boot_safe.sum()

        # Compute KL divergence
        kl_array = rel_entr(P_boot_safe, P_haar_safe)
        kl_val: float = float(np.sum(kl_array))

        # Handle numerical issues
        if np.isnan(kl_val) or np.isinf(kl_val):
            kl_val = _MAX_KL_DIVERGENCE

        bootstrap_kls[b] = kl_val

    # Return standard deviation of bootstrap KL values
    return float(np.std(bootstrap_kls, ddof=1))


def _expressibility_score_from_fidelities(
    fidelities: NDArray[np.floating[Any]],
    n_bins: int,
    n_qubits: int,
) -> float:
    """Map a fidelity sample directly to the [0, 1] expressibility score.

    Mirrors the histogram → KL → normalize pipeline used in
    :func:`compute_expressibility` exactly, so it can be invoked from
    the bootstrap CI loop and produce values commensurate with the
    main-path result. Returns ``0.0`` for fidelity arrays that the
    main path would treat as numerically degenerate (saturated bin or
    NaN/Inf KL); this is the same conservative fallback the main path
    uses.
    """
    # Histogram → density → PMF.
    hist, bin_edges = np.histogram(
        fidelities,
        bins=n_bins,
        range=(0.0, 1.0),
        density=True,
    )
    bin_width = bin_edges[1] - bin_edges[0]
    P_enc = hist * bin_width
    P_enc_sum = P_enc.sum()
    if P_enc_sum > _NUMERICAL_EPSILON:
        P_enc = P_enc / P_enc_sum
    else:
        # Degenerate case — fall back to uniform exactly as the main
        # function does. (Logging is intentionally suppressed inside
        # the bootstrap to avoid spamming users.)
        P_enc = np.ones(n_bins, dtype=np.float64) / n_bins

    bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2.0
    P_haar = compute_haar_distribution(n_qubits, bin_centers)

    P_enc_safe = P_enc + _NUMERICAL_EPSILON
    P_haar_safe = P_haar + _NUMERICAL_EPSILON
    P_enc_safe = P_enc_safe / P_enc_safe.sum()
    P_haar_safe = P_haar_safe / P_haar_safe.sum()

    kl_array = rel_entr(P_enc_safe, P_haar_safe)
    kl = float(np.sum(kl_array))
    if not np.isfinite(kl) or kl < 0.0:
        kl = max(0.0, kl) if np.isfinite(kl) else _MAX_KL_DIVERGENCE
    score = 1.0 - min(1.0, kl / _MAX_KL_DIVERGENCE)
    return float(np.clip(score, 0.0, 1.0))


def _bootstrap_expressibility_ci(
    fidelities: NDArray[np.floating[Any]],
    n_bins: int,
    n_qubits: int,
    rng: np.random.Generator,
    n_bootstrap: int,
    confidence_level: float,
) -> tuple[float, float]:
    """Percentile bootstrap CI on the expressibility score.

    The score is a non-linear function of the fidelity sample (mean of
    a histogram → KL → 1 - min(1, KL/MAX_KL)) so a simple bootstrap of
    a single scalar would miss the histogram non-linearity. We
    instead resample the fidelities and recompute the full score per
    resample.
    """
    n = len(fidelities)
    if n < 2:
        score = _expressibility_score_from_fidelities(fidelities, n_bins, n_qubits)
        return score, score

    indices = rng.integers(0, n, size=(n_bootstrap, n))
    boot_scores: NDArray[np.float64] = np.empty(n_bootstrap, dtype=np.float64)
    for b in range(n_bootstrap):
        boot_scores[b] = _expressibility_score_from_fidelities(
            fidelities[indices[b]], n_bins, n_qubits
        )
    alpha = 1.0 - float(confidence_level)
    lower = float(np.percentile(boot_scores, 100.0 * (alpha / 2.0)))
    upper = float(np.percentile(boot_scores, 100.0 * (1.0 - alpha / 2.0)))
    if upper < lower:
        upper = lower
    return lower, upper
